global:
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
    - targets: [localhost:9090]
  - job_name: sense_primary
    scrape_interval: 5s
    static_configs:
    - targets: [sense_primary:8001]
  - job_name: sense_secondary
    scrape_interval: 5s
    static_configs:
    - targets: [sense_secondary:8002]
